### ISSUE TITLE
Missing file autoload.php

### ISSUE THREAD

**Issue by burgil** [textmagic/textmagic-rest-php-v2#3]
Hi there, It looks like the file mentioned on the README.md is no where to be found,
# Where is it?
![image](https://user-images.githubusercontent.com/41600149/188065033-08654ca3-112d-4a74-87a2-ba19185d93c1.png)

Here's a full search I conducted on Visual Studio Code:
![image](https://user-images.githubusercontent.com/41600149/188064442-b259764b-aa84-4fdf-827a-36642b07f303.png)

I am trying to manually install the repo onto my WordPress site and include it using the following tutorial: https://github.com/textmagic/textmagic-rest-php-v2#usage-example

I just migrated my code to TextMagic from Twilio, Twilio PHP SDK have an autoload.php file I was using successfully:
![image](https://user-images.githubusercontent.com/41600149/188064875-db056c0e-f94b-4983-bc3e-ad45da5747cc.png)

But here I can't find it no where:
![image](https://user-images.githubusercontent.com/41600149/188064927-13a1588e-66f2-427f-a0b9-87668783680d.png)

**Comment by dmitry-textmagic** [comment]
Hi @burgil, the autoloader (vendor/autoload.php) is generated by Composer. Please refer to this documentation: https://getcomposer.org/doc/01-basic-usage.md

**Comment by burgil** [comment]
Thanks
